version: '3.1'
services:
  insight:
    image: nathanls/insight:latest
    environment:
      DB_DRIVER: "sqlite3"
      SQLITE_DB_PATH: "Database.db"
      HEADERS_FROM_EMAIL: "YourEmailHere"
      DISCORD_TOKEN: "OTc1NDAyODg3Mzg5Nzk4NDMw.GtGNsk.Cyb0evkdvFE3NMEwktuNicv84JA75Q3ZT5rCMQ"
      CCP_CLIENT_ID: "3b3c607af9814946b423cf3e71b52768"
      CCP_SECRET_KEY: "z3kykdAO2aVY4ejiAG5mZZ5Oz4NNfBsIVzXIEYMp"
      CCP_CALLBACK_URL: "https://github.eveinsight.net/Insight/callback"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "pass"
      REDIS_PURGE: "FALSE"
      REDIS_SSL: "FALSE"
      INSIGHT_ADMINS: "Dex#7252; AnotherAdminUserID"
      WEBSERVER_ENABLED: "FALSE"
    volumes:
      - insight-data:/app
  redis:
    image: redis:6
    command: --requirepass "pass"
volumes:
  insight-data: