version: '3.1'
services:
  insight:
    image: nathanls/insight:latest
    environment:
      DB_DRIVER: "sqlite3"
      SQLITE_DB_PATH: "Database.db"
      HEADERS_FROM_EMAIL: "YourEmailHere"
      DISCORD_TOKEN: ""
      CCP_CLIENT_ID: ""
      CCP_SECRET_KEY: ""
      CCP_CALLBACK_URL: ""
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "pass"
      REDIS_PURGE: "FALSE"
      REDIS_SSL: "FALSE"
      INSIGHT_ADMINS: "AdminUserID; AnotherAdminUserID"
      WEBSERVER_ENABLED: "FALSE"
    volumes:
      - insight-data:/app
  redis:
    image: redis:6
    command: --requirepass "pass"
volumes:
  insight-data:
